apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-notls
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.eventyay.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
  - host: eventyay.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
