kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: celery
  creationTimestamp:
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: celery
    spec:
      containers:
      - name: celery
        image: gcr.io/eventyay/web:latest
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: DEPLOYMENT
          value: 'celery'
        resources: {}
      restartPolicy: Always
