apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: postgres
  labels:
    name: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      envFrom:
      - configMapRef:
          name: postgres
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data
  volumes:
    - name: pg-data
      gcePersistentDisk:
        pdName: staging-pg-data-disk
        fsType: ext4
