---
kind: Service
apiVersion: v1
metadata:
  name: web
  creationTimestamp:
  labels:
    service: web
spec:
  ports:
  - port: 80
    name: "http"
    protocol: TCP
    targetPort: 5000
  selector:
    service: web
  type: LoadBalancer
