kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: web
  creationTimestamp:
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        image: gcr.io/eventyay/web:latest
        command: ["/bin/sh","-c"]
        args: ["./kubernetes/run.sh"]
        livenessProbe:
          httpGet:
            path: /health-check/
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: C_FORCE_ROOT
          value: 'true'
        - name: DEPLOYMENT
          value: 'web'
        resources: {}
      restartPolicy: Always
